import { createRequire } from 'node:module'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { randomBytes } from 'node:crypto'
import assert from 'node:assert/strict'

const require = createRequire(resolve('web/package.json'))
const { chromium, expect: baseExpect } = require('@playwright/test')
const expect = baseExpect.configure({ timeout: 15000 })
const base = process.env.DONGBA_E2E_BASE_URL || 'http://127.0.0.1:5317'
const apiBase = process.env.DONGBA_E2E_API_URL || 'http://127.0.0.1:8011/api/v1'
assert.equal(new URL(apiBase).port, '8011', 'Acceptance writes must target the isolated API')
assert.equal(new URL(base).port, '5317', 'Acceptance browser must use its dedicated port')
const artifacts = resolve('runtime/e2e')
await mkdir(artifacts, { recursive: true })
const checks = []
const browserErrors = []
const runId = `${Date.now()}`
const name = `测试验收${runId.slice(-7)}`
const browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE })
const context = await browser.newContext({ viewport: { width: 1440, height: 960 }, locale: 'zh-CN' })
const page = await context.newPage()
page.on('pageerror', error => browserErrors.push(error.message))
const credentialsFile = resolve(artifacts, 'credentials.json')
let credentials
try { credentials = JSON.parse(await readFile(credentialsFile, 'utf8')) } catch { credentials = { username: `e2e_admin_${runId}`, password: randomBytes(24).toString('base64url'), display_name: '浏览器验收管理员' }; await writeFile(credentialsFile, JSON.stringify(credentials), { mode: 0o600 }) }
const record = label => { checks.push(label); console.log(`PASS ${label}`) }
let adminToken
async function request(path, body, token = adminToken, method = body === undefined ? 'GET' : 'POST', expected = 200) {
  const response = await fetch(`${apiBase}${path}`, { method, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(body === undefined ? {} : { 'Content-Type': 'application/json' }) }, body: body === undefined ? undefined : JSON.stringify(body) })
  const result = await response.json()
  assert.equal(response.status, expected, `${method} ${path}: ${result.code || ''} ${result.message || ''}`)
  return result
}
async function open(path, heading) {
  await page.goto(`${base}${path}`, { waitUntil: 'networkidle' })
  await expect(page.getByRole('heading', { name: heading, exact: true })).toBeVisible()
}
async function screenshot(label) { await expect(page.locator('.el-loading-mask:visible')).toHaveCount(0); await page.evaluate(() => document.fonts.ready); await page.screenshot({ path: resolve(artifacts, `${label}.png`), fullPage: true, animations: 'disabled' }) }
async function login(user) {
  await page.goto(`${base}/login`, { waitUntil: 'networkidle' })
  await page.getByLabel('登录账号', { exact: true }).fill(user.username)
  await page.getByLabel('密码', { exact: true }).fill(user.password)
  await page.getByRole('button', { name: '登录', exact: true }).click()
  await page.waitForURL(/\/(admin|merchant)\/dashboard$/)
  if (user.username === credentials.username) adminToken = await page.evaluate(() => sessionStorage.getItem('dongba_access_token'))
}
async function logout() { await page.getByRole('button', { name: '退出登录', exact: true }).click(); await page.waitForURL('**/login') }
async function noOverflow(label) {
  const dimensions = await page.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth }))
  assert.ok(dimensions.scroll <= dimensions.width + 1, `${label} horizontal overflow: ${JSON.stringify(dimensions)}`)
  record(`${label} no horizontal page overflow`)
}
try {
  await page.goto(base, { waitUntil: 'networkidle' })
  assert.ok((await page.title()).includes('东巴寻迹'), 'Refusing to act on unrelated app')
  const setup = await request('/auth/setup-status', undefined, null)
  if (setup.setup_required) {
    await expect(page.getByRole('heading', { name: '创建管理员' })).toBeVisible()
    await page.getByLabel('管理员姓名', { exact: true }).fill(credentials.display_name)
    await page.getByLabel('登录账号', { exact: true }).fill(credentials.username)
    await page.getByLabel('密码', { exact: true }).fill(credentials.password)
    await page.getByRole('button', { name: '创建并进入工作台' }).click()
    await page.waitForURL('**/admin/dashboard')
    record('first administrator setup through UI')
    await logout()
  }
  await login(credentials)
  await expect(page.getByRole('heading', { name: '运营概览', exact: true })).toBeVisible()
  adminToken = await page.evaluate(() => sessionStorage.getItem('dongba_access_token'))
  assert.ok(adminToken)
  record('administrator login and role navigation')
  await screenshot('dongba-admin-desktop')
  await noOverflow('admin desktop')

  const fixture = await context.newPage()
  await fixture.setContent('<canvas width="256" height="256"></canvas>')
  const imageData = await fixture.evaluate(() => { const canvas = document.querySelector('canvas'); const ctx = canvas.getContext('2d'); ctx.fillStyle = '#fff'; ctx.fillRect(0,0,256,256); ctx.strokeStyle = '#176b63'; ctx.lineWidth = 5; ctx.strokeRect(30,30,196,196); ctx.fillStyle = '#176b63'; ctx.font = 'bold 30px Arial'; ctx.fillText('TEST ONLY',37,137); return canvas.toDataURL('image/png').split(',')[1] })
  const fixturePath = resolve(artifacts, 'synthetic-test-image.png')
  await writeFile(fixturePath, Buffer.from(imageData, 'base64'))
  await fixture.close()

  await open('/admin/characters', '东巴字典')
  await page.getByRole('button', { name: '新增词条' }).click()
  let drawer = page.getByRole('dialog')
  const characterId = `E2E_${runId}`
  await drawer.getByLabel('词条编号', { exact: true }).fill(characterId)
  await drawer.getByLabel('中文释义', { exact: true }).fill(`${name}词条`)
  await drawer.getByLabel('一级分类', { exact: true }).fill('自动化测试')
  await drawer.getByLabel('文化摘要', { exact: true }).fill('仅用于隔离数据库验收，不是真实东巴文化资料。')
  await drawer.getByLabel('资料来源', { exact: true }).fill('浏览器测试生成，禁止正式发布使用')
  await drawer.locator('input[type=file]').first().setInputFiles(fixturePath)
  await expect(drawer.getByPlaceholder('图片地址')).toHaveValue(/\/api\/v1\/media\//)
  await expect(drawer.locator('img')).toHaveCount(1)
  await expect.poll(() => drawer.locator('img').evaluate(image => image.naturalWidth)).toBeGreaterThan(0)
  const imageUrl = await drawer.getByPlaceholder('图片地址').inputValue()
  assert.equal((await fetch(`${apiBase.replace('/api/v1','')}${imageUrl}`)).status, 401)
  await drawer.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  let row = page.getByRole('row').filter({ hasText: `${name}词条` })
  await expect(row).toContainText('草稿')
  assert.ok(!(await request('/characters', undefined, null)).items.some(item => item.id === characterId))
  record('dictionary create and authenticated private image preview')
  await row.getByRole('button', { name: '编辑', exact: true }).click()
  drawer = page.getByRole('dialog')
  await drawer.getByLabel('文化故事', { exact: true }).fill('编辑后保存的测试资料。')
  await drawer.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  for (const action of ['审核通过', '发布']) {
    await row.getByRole('button', { name: '更多操作' }).click()
    await page.getByRole('menuitem', { name: action, exact: true }).click()
    await expect(row).toContainText(action === '发布' ? '已发布' : '已审核')
  }
  assert.ok((await request('/characters', undefined, null)).items.some(item => item.id === characterId))
  assert.equal((await fetch(`${apiBase.replace('/api/v1','')}${imageUrl}`)).status, 200)
  record('dictionary edit, review and publish; published media becomes public')
  await screenshot('dongba-dictionary-desktop')

  await open('/admin/merchants', '商户管理')
  await page.getByRole('button', { name: '新增商户' }).click()
  drawer = page.getByRole('dialog')
  await drawer.getByLabel('门店名称', { exact: true }).fill(`${name}门店`)
  await drawer.getByLabel('门店地址', { exact: true }).fill('隔离验收地址，不用于导航')
  await drawer.getByLabel('纬度（GCJ-02）', { exact: true }).fill('26.87')
  await drawer.getByLabel('经度（GCJ-02）', { exact: true }).fill('100.23')
  await drawer.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  row = page.getByRole('row').filter({ hasText: `${name}门店` })
  await row.getByRole('button', { name: '更多操作' }).click()
  await page.getByRole('menuitem', { name: '发布', exact: true }).click()
  await expect(row).toContainText('已发布')
  const merchant = (await request(`/admin/merchants?q=${encodeURIComponent(name)}`)).items.find(item => item.name === `${name}门店`)
  assert.ok(merchant)
  const otherMerchant = await request('/admin/merchants', { name: `${name}隔离门店`, latitude: 26.88, longitude: 100.24, status: 'published' })
  record('merchant creation and publication through UI')

  const merchantAccount = { username: `e2e_merchant_${runId}`, password: randomBytes(24).toString('base64url'), display_name: `${name}商户`, role: 'merchant', merchant_id: merchant.id }
  const otherAccount = { username: `e2e_other_${runId}`, password: randomBytes(24).toString('base64url'), display_name: `${name}其他商户`, role: 'merchant', merchant_id: otherMerchant.id }
  const touristAccount = { username: `e2e_tourist_${runId}`, password: randomBytes(24).toString('base64url'), display_name: `${name}游客`, role: 'tourist' }
  await request('/admin/users', merchantAccount)
  await request('/admin/users', otherAccount)
  const tourist = await request('/admin/users', touristAccount)
  await writeFile(resolve(artifacts, `run-${runId}-accounts.json`), JSON.stringify({ merchantAccount, otherAccount, touristAccount }), { mode: 0o600 })
  const dates = { start_at: new Date(Date.now() - 3600000).toISOString(), end_at: new Date(Date.now() + 86400000).toISOString() }
  const coupon = await request('/admin/coupons', { merchant_id: merchant.id, title: `${name}测试券`, rule: '仅用于自动化核销验收，无经济价值', stock: 3, per_user_limit: 1, ...dates, status: 'published' })
  const touristLogin = await request('/auth/login', { username: touristAccount.username, password: touristAccount.password }, null)
  const claim = await request(`/coupons/${coupon.id}/claim`, {}, touristLogin.access_token)
  const foreignLogin = await request('/auth/login', { username: otherAccount.username, password: otherAccount.password }, null)
  await request('/coupons/verify', { code: claim.code }, foreignLogin.access_token, 'POST', 404)
  record('cross-merchant coupon redemption rejected by real API')

  await logout()
  await login(merchantAccount)
  await expect(page.getByRole('heading', { name: '经营概览', exact: true })).toBeVisible()
  assert.equal(await page.getByRole('link', { name: '账号与权限', exact: true }).count(), 0)
  await page.goto(`${base}/admin/users`)
  await page.waitForURL('**/merchant/dashboard')
  const merchantToken = await page.evaluate(() => sessionStorage.getItem('dongba_access_token'))
  await request('/admin/users', undefined, merchantToken, 'GET', 403)
  record('merchant route and server operations-access guards')
  await open('/merchant/profile', '门店资料')
  await expect(page.getByLabel('门店名称', { exact: true })).toHaveValue(`${name}门店`)
  assert.equal(await page.getByLabel('商户质量评分', { exact: true }).count(), 0)
  await open('/merchant/products', '商品管理')
  await page.getByRole('button', { name: '新增商品' }).click()
  drawer = page.getByRole('dialog')
  await drawer.getByLabel('商品名称', { exact: true }).fill(`${name}商品`)
  await drawer.getByLabel('价格（元）', { exact: true }).fill('12.50')
  assert.equal(await drawer.getByLabel('所属商户', { exact: true }).count(), 0)
  await drawer.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: `${name}商品` })).toContainText('草稿')
  const product = (await request('/merchant/products', undefined, merchantToken)).items.find(item => item.name === `${name}商品`)
  await request(`/merchant/products/${product.id}`, { name: '越权修改' }, foreignLogin.access_token, 'PATCH', 404)
  record('merchant product creation requires review; ownership cannot be crossed')

  await open('/merchant/tag-claims', '文化标签')
  await page.getByRole('button', { name: '申请关联' }).click()
  drawer = page.getByRole('dialog')
  await drawer.getByRole('combobox').fill(name)
  await page.getByRole('option', { name: `${name}词条`, exact: true }).click()
  await drawer.getByRole('button', { name: '提交申请' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('row').filter({ hasText: characterId })).toContainText('待审核')
  record('merchant cultural tag application through UI')

  await open('/merchant/redeem', '到店核销')
  await page.getByLabel('核销码', { exact: true }).fill(claim.code)
  await page.getByRole('button', { name: '确认核销' }).click()
  await expect(page.getByText('核销成功', { exact: true })).toBeVisible()
  await page.getByLabel('核销码', { exact: true }).fill(claim.code)
  await page.getByRole('button', { name: '确认核销' }).click()
  await expect(page.getByText('该券已核销', { exact: true })).toBeVisible()
  assert.equal((await request('/merchant/stats', undefined, merchantToken)).redemptions >= 1, true)
  record('coupon redemption and repeat idempotency through UI')
  await screenshot('dongba-redemption-desktop')
  await open('/merchant/dashboard', '经营概览')
  await screenshot('dongba-merchant-desktop')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('navigation', { name: '主导航' })).toBeHidden()
  await expect.poll(() => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(1)
  await noOverflow('merchant mobile dashboard')
  await screenshot('dongba-merchant-mobile')
  await page.getByRole('button', { name: '打开导航' }).click()
  await expect(page.locator('.sidebar-scrim')).toBeVisible()
  await expect(page.getByRole('button', { name: '关闭导航' })).toBeVisible()
  await screenshot('dongba-mobile-navigation-open')
  await page.getByRole('button', { name: '关闭导航' }).click()
  await expect(page.getByRole('navigation', { name: '主导航' })).toBeHidden()
  await page.getByRole('button', { name: '打开导航' }).click()
  await page.getByRole('navigation', { name: '主导航' }).getByRole('link', { name: '到店核销', exact: true }).click()
  await expect(page.getByRole('heading', { name: '到店核销', exact: true })).toBeVisible()
  await noOverflow('merchant mobile redemption')
  await screenshot('dongba-redemption-mobile')
  await page.setViewportSize({ width: 1440, height: 960 })
  await logout()
  await login(credentials)
  await open('/admin/tag-claims', '文化标签审核')
  row = page.getByRole('row').filter({ hasText: characterId })
  await row.getByRole('button', { name: '审核', exact: true }).click()
  drawer = page.getByRole('dialog')
  await drawer.getByLabel('审核意见', { exact: true }).fill('隔离测试审核通过，不代表真实文化审核')
  await drawer.getByRole('button', { name: '提交审核' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(row).toContainText('已通过')
  record('operations approves merchant culture tag through UI')

  const reward = await request('/admin/coupons', { merchant_id: merchant.id, title: `${name}路线奖励`, rule: '隔离测试奖励，无经济价值', stock: 5, per_user_limit: 1, ...dates, status: 'published' })
  await open('/admin/quests', '寻迹路线')
  await page.getByRole('button', { name: '新增路线' }).click()
  drawer = page.getByRole('dialog')
  await drawer.getByLabel('路线名称', { exact: true }).fill(`${name}路线`)
  await drawer.getByLabel('所在区域', { exact: true }).fill('隔离验收区域')
  for (const [label, date] of [['开始时间', new Date(Date.now() - 3600000)], ['结束时间', new Date(Date.now() + 86400000)]]) {
    const text = `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')} ${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`
    await drawer.getByLabel(label, { exact: true }).fill(text)
    await drawer.getByLabel(label, { exact: true }).press('Tab')
  }
  await drawer.getByLabel('完成奖励', { exact: true }).click()
  await page.getByRole('option', { name: `${name}路线奖励`, exact: true }).click()
  await drawer.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  row = page.getByRole('row').filter({ hasText: `${name}路线` })
  await row.getByRole('button', { name: '更多操作' }).click()
  await page.getByRole('menuitem', { name: '发布', exact: true }).click()
  await expect(row).toContainText('已发布')
  const quest = (await request(`/admin/quests?q=${encodeURIComponent(name)}`)).items.find(item => item.name === `${name}路线`)
  assert.ok(quest)
  await open('/admin/quest-nodes', '任务节点')
  await page.getByRole('button', { name: '新增节点' }).click()
  drawer = page.getByRole('dialog')
  await drawer.getByLabel('所属路线', { exact: true }).click()
  await page.getByRole('option', { name: `${name}路线`, exact: true }).click()
  await drawer.getByLabel('节点名称', { exact: true }).fill(`${name}人工节点`)
  await drawer.getByLabel('完成条件', { exact: true }).press('Enter')
  await page.getByRole('option', { name: '人工确认', exact: true }).click()
  await drawer.getByRole('button', { name: '保存', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  row = page.getByRole('row').filter({ hasText: `${name}人工节点` })
  await row.getByRole('button', { name: '更多操作' }).click()
  await page.getByRole('menuitem', { name: '发布', exact: true }).click()
  await expect(row).toContainText('已发布')
  const qrNode = await request('/admin/quest-nodes', { quest_id: quest.id, name: `${name}扫码节点`, sequence: 2, condition: 'qr', status: 'published' })
  await open('/admin/quest-nodes', '任务节点')
  let qrRow = page.getByRole('row').filter({ hasText: `${name}扫码节点` })
  await qrRow.getByRole('button', { name: '更多操作' }).click()
  await page.getByRole('menuitem', { name: '任务二维码', exact: true }).click()
  drawer = page.getByRole('dialog')
  await expect(drawer.getByRole('img', { name: '任务节点二维码' })).toHaveAttribute('src', /^data:image\/png;base64,/)
  const qrDownload = page.waitForEvent('download')
  await drawer.getByRole('button', { name: '下载二维码' }).click()
  await (await qrDownload).saveAs(resolve(artifacts, 'dongba-quest-node-code.png'))
  await screenshot('dongba-quest-qr-desktop')
  await drawer.getByRole('button', { name: '关闭', exact: true }).click()
  await request(`/quests/${quest.id}/join`, {}, touristLogin.access_token)
  await request(`/quests/${quest.id}/checkin`, { node_id: qrNode.id, qr_token: qrNode.qr_token }, touristLogin.access_token)
  record('operations task QR preview and download; tourist QR token checkin')
  row = page.getByRole('row').filter({ hasText: `${name}人工节点` })
  await row.getByRole('button', { name: '更多操作' }).click()
  await page.getByRole('menuitem', { name: '人工确认打卡', exact: true }).click()
  drawer = page.getByRole('dialog')
  await drawer.getByLabel('游客用户编号', { exact: true }).fill(tourist.id)
  await drawer.getByRole('button', { name: '确认完成', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const stamps = await request('/me/stamps', undefined, touristLogin.access_token)
  assert.ok(stamps.items.some(stamp => stamp.quest_id === quest.id))
  const rewards = await request('/me/coupons', undefined, touristLogin.access_token)
  assert.equal(rewards.items.filter(item => item.coupon_id === reward.id).length, 1)
  assert.ok((await request('/admin/stats')).quest_completions >= 1)
  record('route and manual node UI creation, tourist joins, admin checkin grants one stamp and coupon reward')
  await screenshot('dongba-quest-desktop')
  await request(`/me/favorites/${characterId}`, undefined, touristLogin.access_token, 'PUT')
  const poster = await request('/share/poster', { character_ids: [characterId], template: 'paper' }, touristLogin.access_token)
  assert.equal(poster.share_code_available, false)
  await request('/events', { event: 'share', event_id: `e2e-share-${runId}`, entity_type: 'quests', entity_id: quest.id }, touristLogin.access_token)
  await open('/admin/dashboard', '运营概览')
  const businessStats = await request('/admin/stats')
  assert.ok(businessStats.events.poster_generate >= 1)
  assert.ok(businessStats.events.share >= 1)
  await expect(page.getByText('海报生成', { exact: true })).toBeVisible()
  await expect(page.getByText('分享操作', { exact: true })).toBeVisible()
  await screenshot('dongba-admin-desktop')
  record('poster generation and share-action events appear in operations metrics; WeChat code unavailable remains explicit')

  for (const [path, heading] of [['/admin/pois','文化地图点位'],['/admin/activities','体验活动'],['/admin/quests','寻迹路线'],['/admin/quest-nodes','任务节点'],['/admin/feedback','识别纠错'],['/admin/recognitions','识别记录'],['/admin/provider','识别服务'],['/admin/audit','操作审计'],['/admin/users','账号与权限']]) await open(path, heading)
  record('all remaining operations routes render without runtime errors')
  await open('/admin/settings', '推荐配置')
  await expect(page.getByText('合计 100%', { exact: true })).toBeVisible()
  const settingsResponse = page.waitForResponse(response => response.url().endsWith('/admin/settings') && response.request().method() === 'PATCH')
  await page.getByRole('button', { name: '保存配置' }).click()
  assert.equal((await settingsResponse).status(), 200)
  record('recommendation weights save through UI')
  await open('/admin/characters', '东巴字典')
  await page.getByRole('textbox', { name: '搜索', exact: true }).fill(name)
  await page.getByRole('button', { name: '查询', exact: true }).click()
  await expect(page.getByRole('row').filter({ hasText: `${name}词条` })).toHaveCount(1)
  if (process.env.DONGBA_E2E_EXPORTS === '1') {
    const downloadEvent = page.waitForEvent('download')
    await page.getByRole('button', { name: '导出记录' }).click()
    const download = await downloadEvent
    await download.saveAs(resolve(artifacts, 'reviewed-records.csv'))
    const exported = await readFile(resolve(artifacts, 'reviewed-records.csv'), 'utf8')
    assert.ok(exported.includes(characterId))
    const audit = await request('/admin/audit?q=export')
    assert.ok(audit.items.some(item => item.action === 'export'))
    record('filtered CSV download and server export audit')
  }
  row = page.getByRole('row').filter({ hasText: `${name}词条` })
  await row.getByRole('button', { name: '更多操作' }).click()
  await page.getByRole('menuitem', { name: '下架停用', exact: true }).click()
  await page.getByRole('button', { name: '停用', exact: true }).click()
  await expect(row).toContainText('已停用')
  record('soft deletion keeps auditable record and disables publication')
  await page.setViewportSize({ width: 390, height: 844 })
  await noOverflow('operations mobile table')
  await screenshot('dongba-dictionary-mobile')
  await page.getByRole('button', { name: '新增词条' }).click()
  await noOverflow('operations mobile editor')
  await screenshot('dongba-editor-mobile')
  await page.getByRole('button', { name: '取消', exact: true }).click()
  assert.deepEqual(browserErrors, [], 'Browser runtime errors occurred')
  const untouched = await fetch('http://127.0.0.1:8010/api/v1/auth/setup-status').then(response => response.json())
  assert.equal(untouched.setup_required, true, 'Development DB must remain awaiting first admin setup')
  record('normal development database remains untouched')
  await writeFile(resolve(artifacts, 'acceptance-result.json'), JSON.stringify({ at: new Date().toISOString(), base, api: apiBase, checks, browserErrors, synthetic_data_only: true }, null, 2))
  console.log(`SUCCESS ${checks.length} browser and integrated API checks`)
} catch (error) {
  await page.screenshot({ path: resolve(artifacts, 'dongba-failure.png'), fullPage: true }).catch(() => {})
  await writeFile(resolve(artifacts, 'acceptance-failure.json'), JSON.stringify({ at: new Date().toISOString(), checks, error: error.message, browserErrors }, null, 2))
  throw error
} finally { await browser.close() }
